server:
  ip: "127.0.0.1"
  port: "60051"

etcd:
  host: "127.0.0.1"
  port: "2379"

federated:
  num_clients: 3
  num_epochs: 10
  method: "1bit-cs-fl" 
  # method : "fedavg"
  # Options: "baseline", "fedavg", "sign-sgd", "cs-fl", "1bit-cs-fl"

paths:
  # Where trained models are saved
  model_storage: "models" 
  # Where the dataset is stored
  data_dir: "data"

method_args:
  sparsity_thresh: 0.005
  compression_ratio: 0.05
  lr_1: 0.1
  lr_2: 0.002