etcd:
  host: 127.0.0.1
  port: '2379'
experiment_name: compression_impact_0.1
federated:
  method: 1bit-cs-fl
  num_clients: 3
  num_epochs: 5
method_args:
  compression_ratio: 0.1
  lr_1: 0.1
  lr_2: 0.002
  sparsity_thresh: 0.005
paths:
  data_dir: data
  model_storage: models
  results_dir: results
server:
  ip: 127.0.0.1
  port: '60051'
